name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: Describe the problem before the solution.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like to happen?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered
